name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 17
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - run: npm install
      - run: npm run copy:web
             - run: npm install
      
      # Ye step add karo (Make sure tumhare package.json mein build script ho)
      - name: Build Web App
        run: npm run build 

      - run: npx cap add android

      - run: |
          if [ ! -d android ]; then npx cap add android; fi
      - run: npx cap sync android
      - run: cd android && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
